version: 5.1.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nuget_token:
    secure: BzdLe9enAWcmUiOBMdx02CYt2T+xuLGlvieE2+Ceic8tmFpEb06EOlikWdyOxxbf
  github_token:
    secure: 2LiLyCv5qwnAClSid16P+Yiq+zIyBk+6/Xl1ZDOKz5g6ab2vXosiY3m93n52q1WX
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore .\Leaf.xNet.sln
build:
  project: Leaf.xNet.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Leaf.xNet\bin\Release\net452
  name: net452
- path: Leaf.xNet\bin\Release\net462
  name: net462
- path: Leaf.xNet\bin\Release\net471
  name: net471
- path: Leaf.xNet\bin\Release\net472
  name: net472
- path: Leaf.xNet\bin\Release\netcoreapp2.0
  name: netcoreapp2.0
- path: Leaf.xNet\bin\Release\netcoreapp2.1
  name: netcoreapp2.1
- path: Leaf.xNet\bin\Release\netcoreapp2.2
  name: netcoreapp2.2
deploy:
- provider: NuGet
  api_key:
    secure: LAP1RRHzZP5slfjtjZY7WQ==
  skip_symbols: true
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Leaf.xNet v$(appveyor_build_version)
  auth_token:
    secure: NQtMOO3yB309cDK/pFWRiQ==
  artifact: net452;net462;net471;net472;netcoreapp2.0;netcoreapp2.1;netcoreapp2.2
  on:
    branch: master
only_commits:
  files:
    - appveyor.yml
    - Leaf.xNet.sln
    - Leaf.xNet/Leaf.xNet.csproj
    - Leaf.xNet/**/*.cs
    - Leaf.xNet/**/*.resx
